spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:postgresql://dpg-cng0mh5a73kc73dd574g-a.singapore-postgres.render.com:5432/student_9c9i
    password: AC4M4ybeOEU80aq3EFvBw18SHvOYjBHr
    username: student_9c9i_user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # Spring Security / Queries for AuthenticationManagerBuilder
  security:
    user:
      users-query: SELECT username, password, active FROM "user" WHERE username=?
      roles-query: SELECT username, role FROM "user" WHERE username=?

  # Initialize the database using data.sql script
  initialization-mode: always
